### PR TITLE
Added Ruby version

### PR DESCRIPTION
**Pull request by jwillemsen**
Additions to also provide a Ruby version of the example using R2CORBA

### CODE REVIEW

**Comment by troeger** [comment]
This is getting better and better ;-)

We could add a matrix about product version / operating system version combinations that were tested with all of this.

Do you want to become a contributor to this repo, or is sending pull requests good enough for you ?

**Comment by jwillemsen** [comment]
I tested the C++11 and Ruby versions on Linux (openSuSE 13.2). Personally I would prefer to not put generated code into the git archive, that code can change with each version of the ORB you use.

I don't mind to use pull requests, works easily with github (that is also one of the reasons TAO is now also hosted on github)

**Comment by troeger** [comment]
I thought about the stub / skeleton addition too, but wasn't too sure about how much changing ORB versions would change that code. If this is really a potential problem from your professional experience, then I would agree to remove them and make the IDL compilation a part of the Makefile's.

**Comment by jwillemsen** [comment]
It is something we normally never do, stub/skeleton code has to be compiled each time, it really depends on the ORB vendor how much changed with each release and it could even be that the generation result is platform dependent.

**Comment by troeger** [comment]
Ok, then I will take care of that. Thanks for pointing it out.

**Comment by jwillemsen** [comment]
Ok, great! R2CORBA which I used for the Ruby version is open source, TAOX11 which I used for IDL to C++11 is commercial, but we do provide free-of-charge evaluation licenses for classroom usage.

**Pull request merged**
